matrix:
  include:
  - language: node_js
  - addons:
      apt:
        packages:
        - rsync
        - sshpass
    sudo: true
    dist: trusty
    node_js:
    - "stable"
    branches:
      only:
      - master
    script:
    - cd frontend
    - npm install
    - npm run build
    after_success:
    - rsync -chavzP --rsh="sshpass -p $FTP_PASSWORD ssh -o StrictHostKeyChecking=no -l $FTP_USER" dist/* $FTP_USER@e-sport.ee:/web/www-staging
