CREATE TABLE TICKET_MEMBERS
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  ticketId INT NOT NULL,
  idCode VARCHAR(255) NOT NULL,
  CONSTRAINT TICKET_MEMBERS_TICKETS_id_fk FOREIGN KEY (ticketId) REFERENCES TICKETS (id)
);