ALTER TABLE TICKETS ADD seat INT NULL;

ALTER TABLE TICKET_MEMBERS DROP COLUMN idCode;
ALTER TABLE TICKET_MEMBERS ADD email VARCHAR(256) NOT NULL;
ALTER TABLE TICKET_MEMBERS DROP COLUMN igName;
ALTER TABLE TICKET_MEMBERS ADD igName VARCHAR(256) NOT NULL;

ALTER TABLE TICKET_TYPES DROP FOREIGN KEY TicketTypes_TicketTypes_id_fk;
ALTER TABLE TICKET_TYPES DROP COLUMN name;
ALTER TABLE TICKET_TYPES ADD code VARCHAR(64) NOT NULL;
ALTER TABLE TICKET_TYPES DROP COLUMN cost;
ALTER TABLE TICKET_TYPES DROP COLUMN availableFrom;
ALTER TABLE TICKET_TYPES DROP COLUMN availableUntil;
ALTER TABLE TICKET_TYPES DROP COLUMN parentTicketTypeId;
ALTER TABLE TICKET_TYPES DROP COLUMN atLocationCost;
ALTER TABLE TICKET_TYPES ADD assignedSeating BOOLEAN NOT NULL;

CREATE TABLE TICKET_OFFERINGS (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(63) NOT NULL,
  amountAvailable INT NULL,
  availableFrom DATETIME NULL,
  availableUntil DATETIME NULL,
  availableOnline BOOLEAN NOT NULL,
  promotional BOOLEAN NOT NULL,
  cost DECIMAL(15, 2) NOT NULL,
  ticketTypeId INT NOT NULL,
  FOREIGN KEY (ticketTypeId) REFERENCES TICKET_TYPES(id)
);

ALTER TABLE TICKETS DROP FOREIGN KEY Tickets_TicketTypes_id_fk;
ALTER TABLE TICKETS DROP COLUMN typeId;
ALTER TABLE TICKETS add offeringId INT NOT NULL;
ALTER TABLE TICKETS ADD FOREIGN KEY (offeringId) REFERENCES TICKET_OFFERINGS(id);
