CREATE TABLE TICKET_CERTS
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(16) NOT NULL,
    ticketId INT NOT NULL,
    memberId INT NULL,
    timesUsed INT NOT NULL,
    CONSTRAINT TICKET_CERTS_TICKET_TYPES_ID_fk FOREIGN KEY (ticketId) REFERENCES TICKETS (id),
    CONSTRAINT TICKET_CERTS_TICKET_MEMBERS_ID_fk FOREIGN KEY (memberId) REFERENCES TICKET_MEMBERS (id)
);