ALTER TABLE TICKETS ADD ownerId INT NOT NULL;
ALTER TABLE TICKETS DROP COLUMN ownerEmail;
ALTER TABLE TICKETS DROP COLUMN ownerSteamId;
ALTER TABLE TICKETS ADD FOREIGN KEY (ownerId) REFERENCES USERS(id);