flyway:
    baseline-version: 0
    out-of-order: true
spring:
    datasource:
        driver-class-name: "org.mariadb.jdbc.Driver"
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
    jooq:
        sql-dialect: "MARIADB"

