spring:
    datasource:
        username: "root"
        password: "root"
        url: "jdbc:mariadb://localhost/esport2018spring"
jwt:
    signature:
        key: "RSbGD6WWCFk2ng6Yyf0iDznm4d_illwpGk1TQ61Pn2ixT75Vs9gG72B2wOyVm_61xEuNNRlZHuxlgYatD87v4Q"
email:
    apiKey: "<apiKey>"
    domain: "<domain>"
steam:
    apiKey: "<apiKey>"
